[package]
name = "cli"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "cli"
path = "src/main.rs"

[dependencies]
env_logger.workspace = true
log.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
engine = { path = "../engine" }
